// Code generated by goctl. DO NOT EDIT.
// Source: shorturl.proto

package server

import (
	"context"

	"github.com/Guvanchhojamov/shorturl/gateway/services/shorturlrpc/rpc/internal/logic"
	"github.com/Guvanchhojamov/shorturl/gateway/services/shorturlrpc/rpc/internal/svc"
	"github.com/Guvanchhojamov/shorturl/gateway/services/shorturlrpc/rpc/shorturl"
)

type ShorturlServiceServer struct {
	svcCtx *svc.ServiceContext
	shorturl.UnimplementedShorturlServiceServer
}

func NewShorturlServiceServer(svcCtx *svc.ServiceContext) *ShorturlServiceServer {
	return &ShorturlServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ShorturlServiceServer) Expand(ctx context.Context, in *shorturl.ExpandReq) (*shorturl.ExpandResp, error) {
	l := logic.NewExpandLogic(ctx, s.svcCtx)
	return l.Expand(in)
}

func (s *ShorturlServiceServer) Shorten(ctx context.Context, in *shorturl.ShortenReq) (*shorturl.ShortenResp, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}
