// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: gateway/services/shorturlrpc/protos/shorturl.proto

package shorturl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ShorturlService_Expand_FullMethodName  = "/shorturl.shorturlService/expand"
	ShorturlService_Shorten_FullMethodName = "/shorturl.shorturlService/shorten"
)

// ShorturlServiceClient is the client API for ShorturlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShorturlServiceClient interface {
	Expand(ctx context.Context, in *ExpandReq, opts ...grpc.CallOption) (*ExpandResp, error)
	Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error)
}

type shorturlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShorturlServiceClient(cc grpc.ClientConnInterface) ShorturlServiceClient {
	return &shorturlServiceClient{cc}
}

func (c *shorturlServiceClient) Expand(ctx context.Context, in *ExpandReq, opts ...grpc.CallOption) (*ExpandResp, error) {
	out := new(ExpandResp)
	err := c.cc.Invoke(ctx, ShorturlService_Expand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shorturlServiceClient) Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error) {
	out := new(ShortenResp)
	err := c.cc.Invoke(ctx, ShorturlService_Shorten_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShorturlServiceServer is the server API for ShorturlService service.
// All implementations must embed UnimplementedShorturlServiceServer
// for forward compatibility
type ShorturlServiceServer interface {
	Expand(context.Context, *ExpandReq) (*ExpandResp, error)
	Shorten(context.Context, *ShortenReq) (*ShortenResp, error)
	mustEmbedUnimplementedShorturlServiceServer()
}

// UnimplementedShorturlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShorturlServiceServer struct {
}

func (UnimplementedShorturlServiceServer) Expand(context.Context, *ExpandReq) (*ExpandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expand not implemented")
}
func (UnimplementedShorturlServiceServer) Shorten(context.Context, *ShortenReq) (*ShortenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shorten not implemented")
}
func (UnimplementedShorturlServiceServer) mustEmbedUnimplementedShorturlServiceServer() {}

// UnsafeShorturlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShorturlServiceServer will
// result in compilation errors.
type UnsafeShorturlServiceServer interface {
	mustEmbedUnimplementedShorturlServiceServer()
}

func RegisterShorturlServiceServer(s grpc.ServiceRegistrar, srv ShorturlServiceServer) {
	s.RegisterService(&ShorturlService_ServiceDesc, srv)
}

func _ShorturlService_Expand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorturlServiceServer).Expand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShorturlService_Expand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorturlServiceServer).Expand(ctx, req.(*ExpandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShorturlService_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorturlServiceServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShorturlService_Shorten_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorturlServiceServer).Shorten(ctx, req.(*ShortenReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShorturlService_ServiceDesc is the grpc.ServiceDesc for ShorturlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShorturlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shorturl.shorturlService",
	HandlerType: (*ShorturlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "expand",
			Handler:    _ShorturlService_Expand_Handler,
		},
		{
			MethodName: "shorten",
			Handler:    _ShorturlService_Shorten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/services/shorturlrpc/protos/shorturl.proto",
}
