// Code generated by goctl. DO NOT EDIT.
// Source: shorturl.proto

package shorturlservice

import (
	"context"

	"github.com/Guvanchhojamov/shorturl/gateway/services/shorturlrpc/rpc/shorturl"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExpandReq   = shorturl.ExpandReq
	ExpandResp  = shorturl.ExpandResp
	ShortenReq  = shorturl.ShortenReq
	ShortenResp = shorturl.ShortenResp

	ShorturlService interface {
		Expand(ctx context.Context, in *ExpandReq, opts ...grpc.CallOption) (*ExpandResp, error)
		Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error)
	}

	defaultShorturlService struct {
		cli zrpc.Client
	}
)

func NewShorturlService(cli zrpc.Client) ShorturlService {
	return &defaultShorturlService{
		cli: cli,
	}
}

func (m *defaultShorturlService) Expand(ctx context.Context, in *ExpandReq, opts ...grpc.CallOption) (*ExpandResp, error) {
	client := shorturl.NewShorturlServiceClient(m.cli.Conn())
	return client.Expand(ctx, in, opts...)
}

func (m *defaultShorturlService) Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error) {
	client := shorturl.NewShorturlServiceClient(m.cli.Conn())
	return client.Shorten(ctx, in, opts...)
}
